restro/urls.py
from django.contrib import admin
from django.urls import path,include
from customers.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('home/',home,name="home"),
    path('management/',include('management.urls')),
    path('customers/',include('customers.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

management/models.py
from django.db import models
# python3 manage.py migrate admin <to insialise the table>
# python3 manage.py makemigrations //under suspect
# python3 manage.py makemigrations management < to migrate model into databse>
# python3 manage.py createsupperuser <create db same as phpmyadmin>
# python3 manage.py migrate <to make different changes at a runtime>
class category(models.Model):
    name=models.CharField(max_length=35)
    def __str__(self):
        return self.name

class dish(models.Model):
    cat=models.ForeignKey(category,on_delete=models.CASCADE)
    title=models.CharField(max_length=50,blank=True, null=True)
    price=models.IntegerField(blank=True, null=True)
    mrp=models.IntegerField(blank=True, null=True)
    img=models.ImageField(blank=True, null=True)
    img1=models.ImageField(blank=True, null=True)
    img2=models.ImageField(blank=True, null=True)
    dis=models.TextField(blank=True, null=True)
    avail=models.BooleanField(blank=True, null=True)
    def __str__(self):
        return self.title + '---' + str(self.cat.name)  

class contacts(models.Model):
    name=models.CharField(max_length=50,blank=True, null=True)
    email=models.EmailField(max_length=254,blank=True, null=True)
    subject=models.CharField(max_length=50,blank=True, null=True)
    message=models.TextField(blank=True, null=True)
    def __str__(self):
        return self.name + '---' + str(self.email)
    

templates/about.html
{% extends 'base.html' %} {% load static %} {% block body %}

<section class="page_header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="text-uppercase wow fadeInDown">About us</h2>
                <p class="wow fadeInUp">Read our Story, How we started and about the Team</p>
            </div>
        </div>
    </div>
</section>

<section class="about2">
    <div class="container">
        <div class="row wow fadeInUp">
            <div class="col-md-5">
                <img src="{% static 'img/about.png' %}" class="img-responsive" alt="" />
            </div>
            <div class="col-md-7 text-left">
                <h2 class="text-left">Our Story</h2>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen
                    book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passage</p>
                <a class="btn btn-default" role="button" href="#menu">See Our Menu</a>
            </div>
        </div>
    </div>
</section>

<section class="services">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header wow fadeInDown">
                    <h1 class="white">Special Service<small>What Special services we are offering now</small></h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="services-slider wow fadeIn">
                    <div class="service-content text-center">
                        <img src="{% static 'img/ico1.png' %}" class="center-block" alt="" />
                        <h4 class="text-uppercase">Birthday Party</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
                    </div>
                    <div class="service-content text-center">
                        <img src="{% static 'img/ico2.png' %}" class="center-block" alt="" />
                        <h4 class="text-uppercase">Wedding Party</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer.</p>
                    </div>
                    <div class="service-content text-center">
                        <img src="{% static 'img/ico1.png' %}" class="center-block" alt="" />
                        <h4 class="text-uppercase">Birthday Party</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard dummy text ever since the 1500s, when an unknown printer.</p>
                    </div>
                    <div class="service-content text-center">
                        <img src="{% static 'img/ico2.png' %}" class="center-block" alt="" />
                        <h4 class="text-uppercase">Wedding Party</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text when an unknown printer.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="team">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header wow fadeInDown">
                    <h1>Our Team<small>The Hardworking Team behind the restaurant</small></h1>
                </div>
            </div>
        </div>
        <div class="row">

            {% for i in team %}
            <div class="col-md-3 col-sm-6 text-center">
                <div class="team-staff wow fadeInUp" data-wow-delay="0.2s">
                    <img src="{{ i.img.url }}" class="img-responsive center-block" alt="" />
                    <h4>{{i.name}}</h4>
                    <p>{{i.designation}}</p>
                    <ul class="team-social">
                        <li><a href="{{i.fb}}"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="{{i.twt}}"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="{{i.insta}}"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>
<div class="trusted">

    <div class="trusted-quote">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-1 col-md-10 wow fadeIn">
                    <div class="trusted-slider">
                        <ul class="slides">
                            <li>
                                <img src="{% static 'img/quote.png' %}" alt="quote">
                                <p class="quote-body">The world’s a big, big stage for this notorious deli smack in the middle of the theatre district, infamously famous for its over-the-top corned beef and pastrami sandwiches, chopped liver, blintzes, celebrities, salami,
                                    smoked fish and New York’s finest cheesecake.</p>
                                <p class="quote-author">Anthony Reed, <span>New York</span></p>
                            </li>
                            <li>
                                <img src="{% static 'img/quote.png' %}" alt="quote">
                                <p class="quote-body">You might not find dragon meat on the menu, but you’ll find pretty much anything else that walks, swims or flies, cooked up in more ways than there are people in the Guangdong province. This Midtown mainstay has a 20-year
                                    history of delivering mouth-watering and Cantonese style chow.</p>
                                <p class="quote-author">Gemma Arterton, <span>Bay Area</span></p>
                            </li>
                            <li>
                                <img src="{% static 'img/quote.png' %}" alt="quote">
                                <p class="quote-body">This NYC historical landmark in the heart of the Theatre District has been serving up suds and down home pub food since 1892, surviving prohibition by renting the front of its then Rockefeller Center façade to Greek florists,
                                    while the Hurley brothers ran a speak-easy in back.</p>
                                <p class="quote-author">Zachary Burton, <span>Sanfransisco</span></p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="menu space60" id="menu">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header wow fadeInDown">
                    <h1>Our menu<small>These fine folks trusted the award winning restaurant.</small></h1>
                </div>
            </div>
        </div>
        <div class="food-menu wow fadeInUp">
            <div class="row">
                <div class="col-md-12">
                    <div class="menu-tags">
                        <span data-filter="*" class="tagsort-active">All</span>
                        <span data-filter=".starter">starters</span>
                        <span data-filter=".breakfast">breakfast</span>
                        <span data-filter=".lunch">lunch</span>
                        <span data-filter=".dinner">dinner</span>
                        <span data-filter=".desserts">desserts</span>
                    </div>
                </div>
            </div>
            <div class="row menu-items">
                <div class="menu-item col-sm-6 col-xs-12 starter dinner desserts">
                    <div class="clearfix menu-wrapper">
                        <h4>English asparagus</h4>
                        <span class="price">$14.95</span>
                        <div class="dotted-bg"></div>
                    </div>
                    <p>pellentesque enim. Aliquam tempor</p>
                </div>
                <div class="menu-item col-sm-6 col-xs-12 starter">
                    <div class="clearfix menu-wrapper">
                        <h4>English asparagus</h4>
                        <span class="price">$14.95</span>
                        <div class="dotted-bg"></div>
                    </div>
                    <p>pellentesque enim. Aliquam tempor</p>
                </div>
                <div class="menu-item col-sm-6 col-xs-12 breakfast desserts starter">
                    <div class="clearfix menu-wrapper">
                        <h4>English asparagus</h4>
                        <span class="price">$14.95</span>
                        <div class="dotted-bg"></div>
                    </div>
                    <p>pellentesque enim. Aliquam tempor</p>
                </div>
                <div class="menu-item col-sm-6 col-xs-12 breakfast">
                    <div class="clearfix menu-wrapper">
                        <h4>English asparagus</h4>
                        <span class="price">$14.95</span>
                        <div class="dotted-bg"></div>
                    </div>
                    <p>pellentesque enim. Aliquam tempor</p>
                </div>
                <div class="menu-item col-sm-6 col-xs-12 lunch starter breakfast featured">
                    <div class="clearfix menu-wrapper">
                        <h4>English asparagus</h4>
                        <span class="price">$14.95</span>
                        <div class="dotted-bg"></div>
                    </div>
                    <p>pellentesque enim. Aliquam tempor</p>
                </div>
                <div class="menu-item col-sm-6 col-xs-12 lunch">
                    <div class="clearfix menu-wrapper">
                        <h4>English asparagus</h4>
                        <span class="price">$14.95</span>
                        <div class="dotted-bg"></div>
                    </div>
                    <p>pellentesque enim. Aliquam tempor</p>
                </div>
                <div class="menu-item col-sm-6 col-xs-12 dinner breakfast lunch">
                    <div class="clearfix menu-wrapper">
                        <h4>English asparagus</h4>
                        <span class="price">$14.95</span>
                        <div class="dotted-bg"></div>
                    </div>
                    <p>pellentesque enim. Aliquam tempor</p>
                </div>
                <div class="menu-item col-sm-6 col-xs-12 dinner">
                    <div class="clearfix menu-wrapper">
                        <h4>English asparagus</h4>
                        <span class="price">$14.95</span>
                        <div class="dotted-bg"></div>
                    </div>
                    <p>pellentesque enim. Aliquam tempor</p>
                </div>
                <div class="menu-item col-sm-6 col-xs-12 desserts lunch dinner">
                    <div class="clearfix menu-wrapper">
                        <h4>English asparagus</h4>
                        <span class="price">$14.95</span>
                        <div class="dotted-bg"></div>
                    </div>
                    <p>pellentesque enim. Aliquam tempor</p>
                </div>
                <div class="menu-item col-sm-6 col-xs-12 desserts">
                    <div class="clearfix menu-wrapper">
                        <h4>English asparagus</h4>
                        <span class="price">$14.95</span>
                        <div class="dotted-bg"></div>
                    </div>
                    <p>pellentesque enim. Aliquam tempor</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="menu-btn">
                        <a class="btn btn-default btn-lg" href="menu_all.html" role="button">Explore our menu</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body %}

templates/account.html
{% extends "base.html" %} {% block body %} {% load static %}
<section class="page_header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="text-uppercase">Account</h2>
                <p>Please login or signup to continue with your purchase</p>
            </div>
        </div>
    </div>
</section>

<section class="shop-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row shop-login">
                    <div class="col-md-6">
                        <div class="box-content">
                            <h3 class="text-center">Existing Customer</h3>
                            <br>
                            <form class="logregform" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <label>Username or E-mail Address</label>
                                            <input type="text" name="un" value="" class="form-control">
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="row">
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <a class="pull-right" href="index-2.html">(Lost Password?)</a>
                                            <label>Password</label>
                                            <input type="password" name="pass" value="" class="form-control">
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <span class="remember-box checkbox">
                                            {% if errorL %}
                                            <p>Wrong username Password</p>
                                            {% endif %}

                                        </span>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="submit" name="login" class="btn btn-default pull-right">Login</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="box-content">
                            <h3 class="text-center">Register An Account</h3>
                            <br>
                            <form method="POST" class="logregform">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <label>E-mail Address</label>
                                            <input type="email" name="e" value="" class="form-control">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <label>Username</label>
                                            <input type="text" name="un" value="" class="form-control">
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix space20"></div>
                                <div class="row">
                                    <div class="form-group">
                                        <div class="col-md-6">
                                            <label>Password</label>
                                            <input type="password" name="pwd1" value="" class="form-control">
                                        </div>
                                        <div class="col-md-6">
                                            <label>Re-enter Password</label>
                                            <input type="password" name="pwd2" value="" class="form-control">
                                        </div>
                                    </div>
                                </div>
                                {% if errPass %}
                                <span>password in not matching</span> {% endif %} {% if errUn %}
                                <span>username already avaible</span> {% endif %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="space20"></div>
                                        <button type="submit" name="singup" class="btn btn-default pull-right">Register</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock body %}

templates/editCat.html
{% extends "base2.html" %} {% load static %} {% block body %}
<div class="row">
    <div class="col-md-6">
        <div class="page-header">
            <h2>Categiry</h2>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>category</th>

                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in cat %}
                <tr>
                    <th>{{i.name}}</th>
                    <th>{{i.dish_set.count}}</th>
                    <th>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-xs" name="deleteCat" value="{{i.id}}">Delete</button>
                        </form>
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <div class="page-header">
            <h2>Add Category</h2>
        </div>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Category</label>
                <input type="text" name="cat" class="form-control" id="" placeholder="Add Category">
            </div>

            <button type="submit" name="addCategory" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/editDish.html
{% extends 'base2.html' %} {% load static %} {% block body %}
<div class="row container">
    <div class="col-md-6">
        <div class="page-header">
            <h2>Dishes</h2>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>price</th>
                    <th>available</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in dish %}
                <tr>
                    <th>{{i.title}}</th>
                    <th>{{i.price}}</th>
                    {% if i.avail %}
                    <th>Available</th>
                    {% else %}
                    <th>Not available</th>
                    {% endif %}

                    <th>
                        <form action="" method="POST">
                            {% csrf_token %} {% if i.avail %}
                            <button type="submit" class="btn btn-default btn-xs" name="unavail" value="{{i.id}}">unavailable</button> {% else %}
                            <button type="submit" class="btn btn-success btn-xs" name="avail" value="{{i.id}}">Available</button> {% endif %}
                            <button type="submit" class="btn btn-danger btn-xs" name="deleteDish" value="{{i.id}}">Delete</but>
                        </form>
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <div class="page-header">
            <h2>Add Dish</h2>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <select name="cat" class="form-control">
                    <option selected disabled value="">select your category</option>
                    {% for i in cat  %}
                      <option value="{{i.id}}">{{i.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="">Title</label>
                <input type="text" name="title" id="" class="form-control" placeholder="Enter Title">
            </div>
            <div class="form-group">
                <label for="">Mrp</label>
                <input type="text" name="mrp" id="" class="form-control">
            </div>
            <div class="form-group">
                <label for="">Price</label>
                <input type="text" name="price" id="" class="form-control">
            </div>
            <div class="form-group">
                <label for="">image1</label>
                <input type="file" name="img" id="">
            </div>
            <div class="form-group">
                <label for="">image2</label>
                <input type="file" name="img2" id="">
            </div>
            <div class="form-group">
                <label for="">image3</label>
                <input type="file" name="img3" id="">
            </div>
            <div class="form-group">
                <textarea class="form-control" name="dis"></textarea>
            </div>
            <button type="submit" name="addDish" class="btn btn-primary">Submit</button>
                        </form>
    </div>
</div>
{% endblock body %}

templates/editTeams.html
{% extends 'base2.html' %} {% load static %} {% block body %}
<div class="row ">
    <div class="col-md-6">
        <div class="page-header">
            <h2>Teams</h2>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>img</th>
                    <th>name</th>
                    <th>designation</th>
                    <th>facebook</th>
                    <th>instagram</th>
                    <th>twitter</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in team %}
                <tr>
                    <th><img src="{{i.img.url}}" class="" style="width:100px;" /></th>
                    <th>{{i.name}}</th>
                    <th>{{i.designation}}</th>

                    <th><a href="{{i.fb}}"><i class="fa fa-facebook text-info fa-2x"></i></a> </th>
                    <th><a href="{{i.twt}}"><i class="fa fa-twitter fa-2x"></i></a> </th>
                    <th><a href="{{i.insta}}"><i class="fa fa-instagram text-danger fa-2x"></i></a> </th>
                    <th>
                        <form method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-xs" name="teamdel" value="{{i.id}}">Delete
                                </but>
                        </form>
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-md-5">
        <div class="page-header">
            <h2>Add Team</h2>
        </div>
        {% if messages %}
        {% for message in messages %}
        {% if message.tags %}
        <div class="alert alert-info {{ message.tags }}"><span>{{message}}</span>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="">Name</label>
                <input type="text" name="name" id="" class="form-control">
            </div>
            <div class="form-group">
                <label for="">Designation</label>
                <input type="text" name="dest" id="" class="form-control">
            </div>
            <div class="form-group">
                <label for="">facebook <i class="fa fa-facebook"></i></label>
                <input type="text" name="fb" id="" class="form-control">
            </div>
            <div class="form-group">
                <label for="">Twitter <i class="fa fa-twitter"></i></label>
                <input type="text" name="twt" id="" class="form-control">
            </div>
            <div class="form-group">
                <label for="">Instagram <i class="fa fa-instagram"></i></label>
                <input type="text" name="insta" id="" class="form-control">
            </div>
            <div class="form-group">
                <label for="">file <i class="fa fa-file"></i></label>
                <input type="file" name="file" id="" class="form-control">
            </div>
            <button type="submit" name="addTeam" class="btn btn-default">Submit</button>

                        </form>
    </div>
</div>
{% endblock body %}

templates/index2.html
{% extends "base2.html" %} {% load static %} {% block body %}

<div class="row">
    <div class="col-md-7">
        <div class="page-header">
            <h2>Reservation</h2>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Guest</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Confirm</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in res %}
                <tr>
                    <th>{{i.name}}</th>
                    <th>{{i.guests}}</th>
                    <th>{{i.date}}</th>
                    <th>{{i.time}}</th>
                    <th>{{i.confirm}}</th>
                    <th>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-primary btn-xs" name="confirm" value="{{i.id}}">Confirm</button>
                            <button type="submit" class="btn btn-danger btn-xs" name="delete" value="{{i.id}}">Delete</button>
                        </form>
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="col-md-5">
        <div class="page-header">
            <h2>Orders</h2>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Dish</th>
                    <th>price</th>
                    <th>qty</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in orders %}
                <tr>
                    <th>{{i.user.username}}</th>
                    <th>{{i.dish.title}}</th>
                    <th>{{i.dish.price}}</th>
                    <th>{{i.qty}}</th>

                    {% if i.confirm %}
                    <td>paid</td>
                    {% else %}
                    <td>due</td>
                    {% endif %}

                    <th>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-primary btn-xs" name="confirmOrder" value="{{i.id}}">Confirm</button>
                            <button type="submit" class="btn btn-danger btn-xs" name="deleteOrder" value="{{i.id}}">Delete</button>
                        </form>
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


</div>


{% endblock body %}

templates/mail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email</title>
</head>

<body>
    <h2>Hello {{name}}</h2>
    <h3>Welcome to Tomato</h3>
    <p>Your request for reservation of {{guests}} guests on {{date}} at {{time}} has been confirmed</p>
    <p>Thankyou</p>
</body>

</html>